### ISSUE TITLE
the role 'rvm_io.ruby' was not found in [list of paths]

### ISSUE THREAD

**Issue by davemckenna01** [rvm/rvm1-ansible#131] opened 2016-12-28 16:02 UTC
I'm experiencing some strange behaviour when trying to install rvm. Ansible complains that the role 'rvm_io.ruby' was not found in /Users/davemckenna/Development/hdenv_test_1/vagrant/provisioning/roles:/usr/local/etc/ansible/roles:/Users/davemckenna/Development/hdenv_test_1/vagrant/provisioning

But in ansible.cfg I've explicitly set a roles_path = galaxy.roles, which would be at /Users/davemckenna/Development/hdenv_test_1/vagrant/provisioning/galaxy.roles

I have 3 galaxy roles specified in my playbook, like so:

roles:
    ...
    - { role: resmo.ntp, become: yes }
    - { role: rvm_io.ruby, tags: ruby, rvm1_user: '{{ ansible_user }}' }
    - { role: bennojoy.nginx, tags: nginx, become: yes }

and rvm_io.ruby is the only one that complains about not finding the role. The other two are found at provisioning/galaxy.roles with no problem.

When I prefix the role path with "galaxy.roles/", like so:

    - { role: galaxy.roles/rvm_io.ruby, tags: ruby, rvm1_user: '{{ ansible_user }}' }

the role is found and rvm installs.

Is there something unique about rvm_io.ruby that would cause this?

**Comment by lpaulmp** [comment] 2017-01-06 23:40
I'm not able to reproduce the issue, please make sure that you are downloading the correct version.
[rvm_io.ruby](https://galaxy.ansible.com/rvm_io/ruby/)

**Comment by zozo6015** [comment] 2017-01-10 12:20
I have the same issues running it on ubuntu I have role_path configured to /etc/ansible/roles 
installed the role with ansible galaxy and when I run the playbook I get the following error:

[workspace] $ /usr/bin/ansible-playbook ansible/deploy-linkchecker.yml -i hosts -l test2 -f 5 -e deploy_linkchecker=true
[0;31mERROR! the role 'rvm_io.ruby' was not found in /var/lib/jenkins/jobs/DeployTenon/workspace/ansible/roles:/var/lib/jenkins/jobs/DeployTenon/workspace/ansible/roles:/var/lib/jenkins/jobs/DeployTenon/workspace/ansible

The error appears to have been in '/var/lib/jenkins/jobs/DeployTenon/workspace/ansible/deploy-linkchecker.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - pm2
    - { role: rvm_io.ruby,
      ^ here
[0m
FATAL: command execution failed

The playbook looks like this:

roles:
    - pm2
    - { role: rvm_io.ruby,
      rvm1_rvm_version: 'stable',
      rvm1_rubies: '{{ ruby_version }}',
      rvm1_install_flags: '--auto-dotfiles',
      rvm1_install_path: /usr/local/rvm,
      rvm1_user: root
      }

**Comment by manubo** [comment] 2018-10-08 12:12
Might be related to this issue:
https://github.com/rvm/rvm1-ansible/issues/179

**Comment by thbar** [comment] 2020-09-19 10:14
As @manubo pointed out, I believe this is due to naming change. Closing for now, but please re-open if you face that issue.

**Closed by thbar** 2020-09-19 10:14 UTC
