### ISSUE TITLE
Failed to validate the SSL certificate

### ISSUE THREAD

**Issue by demian711** [rvm/rvm1-ansible#44] opened 2015-05-05 20:33 UTC
I was trying to do a fresh install on a totally new EC2 instance (Ubuntu 14) And I am getting a 'Failed to validate the SSL certificate' error on "TASK: [rvm_io.rvm1-ruby | Install rvm installer]". This is the ansible output:
TASK: [rvm_io.rvm1-ruby | Detect rvm installer] ******************************* 
ok: [52.5.52.143]

TASK: [rvm_io.rvm1-ruby | Detect current rvm version] ************************* 
skipping: [52.5.52.143]

TASK: [rvm_io.rvm1-ruby | Install rvm installer] ****************************** 
failed: [52.5.52.143] => {"failed": true, "item": ""}
msg: Failed to validate the SSL certificate for raw.githubusercontent.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting

Thanks

**Comment by nickjj** [comment] 2015-05-07 12:31
I can't reproduce this. Have you tried re-running it?

**Comment by amritsingh** [comment] 2015-07-06 11:05
If you are using ansible version below 1.9 you will face this issue. Please move to the latest version.

**Comment by jonfer** [comment] 2015-08-25 10:56
I also had this problem, upgrading Ansible solved it :thumbsup:

**Comment by nickjj** [comment] 2015-08-25 11:50
Ok thanks guys, going to close this.

**Closed by nickjj** 2015-08-25 11:50 UTC
Labels: feedback needed

**Comment by keyeh** [comment] 2016-02-20 01:16
I'm getting the same error. I'm using the latest ansible 2.1.0 from git on a fresh ubuntu 14.04.4 install
